services:
  mariadb:
    image: mariadb:11
    container_name: clinica_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: zah25
      MARIADB_DATABASE: clinica_medicala
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: